conversations:
  - ["Hi", "Hello! How can I help you today?"]
  - ["Hello", "Hi there! Where would you like to travel?"]
  - ["I want to travel", "Sure! Do you have any destination in mind?"]
  - ["Suggest me a country to visit", "Japan, Italy, and Switzerland are great options depending on your interests."]
  - ["Tell me about Pakistan", "Pakistan is known for its mountains, culture, and hospitality. Must-visit cities: Islamabad, Lahore, Karachi."]
  - ["What are famous tourist attractions in Karachi?", "Clifton Beach, Quaid-e-Azam's Mausoleum, Mohatta Palace, and Pakistan Maritime Museum."]
  - ["How can I book a flight?", "You can book flights through Skyscanner, Kayak, or Google Flights."]
  - ["Tell me a joke", "Why did the scarecrow win an award? Because he was outstanding in his field!"]
  - ["What are some popular travel destinations?", "Paris, Dubai, Tokyo, Istanbul, and Bangkok are very popular destinations."]
  - ["How do I get a visa?", "You can apply for a visa through the official embassy website of the destination country."]
  - ["What's the best time to visit Europe?", "April to June and September to October are ideal for pleasant weather and fewer crowds."]
  - ["Can you help me plan a trip?", "Of course! Tell me your destination, travel dates, and budget."]
  - ["Bye", "Goodbye! Have a great trip!"]
  - ["Thank you", "You're welcome! Safe travels!"]
